# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 490d6780daa10ba24429d0c2cee3b7e8226f071675988ec6e5433570253f6473301612211a42fb6c8f4d91b788ed7db6fe94c4df33a1bdfb6c1483816602066d

test:
  secret_key_base: 0e1340bc379d8aeebb07505e6435092498c769f4a200802d3558912b459d82105f2f916ab1ac4842ed25ced0d5c7492467fc79801d3f40c09e0b29b55fbe71a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
